# Generated by Django 4.2 on 2023-07-27 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_jobcard_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=100)),
                ('error', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('jobcard_type', models.CharField(choices=[('application', 'Application'), ('service', 'Service')], default='service', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in-progress', 'In-Progress'), ('completed', 'Completed')], default='pending', max_length=30)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_employee': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.equipment')),
            ],
        ),
    ]
