# Generated by Django 4.2 on 2023-07-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_ticket_completed_alter_ticket_assigned_to_and_more'),
        ('employees', '0002_alter_employee_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
