# Generated by Django 4.2 on 2023-07-10 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('install_date', models.DateField()),
                ('contract_end', models.DateField()),
                ('status', models.BooleanField()),
                ('first_serv', models.DateField(blank=True, null=True)),
                ('second_serv', models.DateField(blank=True, null=True)),
                ('validation', models.BooleanField(blank=True, null=True)),
                ('contract_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('jobcard_id', models.AutoField(primary_key=True, serialize=False)),
                ('received_by', models.CharField(max_length=30)),
                ('job_start_date', models.DateField()),
                ('job_end_date', models.DateField()),
                ('requested_by', models.CharField(max_length=30)),
                ('ok_checklist', models.CharField(max_length=30, null=True)),
                ('faulty_checklist', models.CharField(max_length=30, null=True)),
                ('spare_used', models.CharField(max_length=30)),
                ('labor_charge', models.CharField(max_length=30)),
                ('total_cost', models.CharField(max_length=30)),
                ('jobcard_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_media', models.FileField(blank=True, null=True, upload_to='jobcards/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_jobcards', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institution')),
            ],
            options={
                'ordering': ('-jobcard_created_at',),
            },
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_tickets', to='core.employee')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('serial_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedJobCard',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('uploaded_media', models.FileField(upload_to='jobcards/')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institution')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='core.institution'),
        ),
        migrations.AddField(
            model_name='employee',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institution'),
        ),
    ]
