# Generated by Django 4.2 on 2023-07-07 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import oauth2_provider.generators
import oauth2_provider.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('eng_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=30)),
                ('inst_name', models.CharField(max_length=30)),
                ('equipment', models.CharField(max_length=30)),
                ('eng_name', models.CharField(max_length=30)),
                ('issue', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('region', models.CharField(max_length=30)),
                ('inst_name', models.CharField(max_length=30)),
                ('equipment', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('install_date', models.DateField()),
                ('contract_end', models.DateField()),
                ('status', models.BooleanField()),
                ('first_serv', models.DateField()),
                ('second_serv', models.DateField()),
                ('validation', models.BooleanField()),
                ('contract_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OAuth2Application',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, default=oauth2_provider.generators.generate_client_id, max_length=100, unique=True)),
                ('redirect_uris', models.TextField(blank=True, help_text='Allowed URIs list, space separated')),
                ('post_logout_redirect_uris', models.TextField(blank=True, help_text='Allowed Post Logout URIs list, space separated')),
                ('client_type', models.CharField(choices=[('confidential', 'Confidential'), ('public', 'Public')], max_length=32)),
                ('authorization_grant_type', models.CharField(choices=[('authorization-code', 'Authorization code'), ('implicit', 'Implicit'), ('password', 'Resource owner password-based'), ('client-credentials', 'Client credentials'), ('openid-hybrid', 'OpenID connect hybrid')], max_length=32)),
                ('client_secret', oauth2_provider.models.ClientSecretField(blank=True, db_index=True, default=oauth2_provider.generators.generate_client_secret, help_text='Hashed on Save. Copy it now if this is a new secret.', max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('skip_authorization', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('algorithm', models.CharField(blank=True, choices=[('', 'No OIDC support'), ('RS256', 'RSA with SHA-2 256'), ('HS256', 'HMAC with SHA-2 256')], default='', max_length=5)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='jobCards',
            fields=[
                ('jobcard_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=30)),
                ('inst_name', models.CharField(max_length=30)),
                ('equipment', models.CharField(max_length=30)),
                ('received_by', models.CharField(max_length=30)),
                ('job_start_date', models.DateField()),
                ('job_end_date', models.DateField()),
                ('requested_by', models.CharField(max_length=30)),
                ('ok_checklist', models.CharField(max_length=30, null=True)),
                ('faulty_checklist', models.CharField(max_length=30, null=True)),
                ('spare_used', models.CharField(max_length=30)),
                ('labor_charge', models.CharField(max_length=30)),
                ('total_cost', models.CharField(max_length=30)),
                ('jobcard_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_media', models.FileField(null=True, upload_to='jobcards/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Engineer', to=settings.AUTH_USER_MODEL)),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipments')),
            ],
            options={
                'ordering': ('-jobcard_created_at',),
            },
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('completed', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_issues', to='core.employees')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipments')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('inst_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=30)),
                ('inst_name', models.CharField(max_length=30)),
                ('equipment', models.CharField(max_length=30)),
                ('install_date', models.DateField()),
                ('error_reported', models.CharField(max_length=30)),
                ('engineer', models.CharField(max_length=30)),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipments')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedJobCards',
            fields=[
                ('jobcardcard_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('inst_name', models.CharField(max_length=30)),
                ('equipment', models.CharField(max_length=30)),
                ('uploaded_media', models.FileField(upload_to='jobcards/')),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipments')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='serial_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipments'),
        ),
    ]
