# Generated by Django 4.2 on 2023-07-22 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('install_date', models.DateField()),
                ('contract_end', models.DateField()),
                ('status', models.BooleanField()),
                ('first_serv', models.DateField(blank=True, null=True)),
                ('validation', models.BooleanField(blank=True, null=True)),
                ('second_serv', models.DateField(blank=True, null=True)),
                ('validation2', models.BooleanField(blank=True, null=True)),
                ('contract_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=100)),
                ('error', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('region', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('upload', models.FileField(blank=True, null=True, upload_to='ticket_photos/%Y/%m/%d/')),
                ('assigned_updated_at', models.DateTimeField(blank=True, null=True)),
                ('marked_complete_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('serial_number', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_by', models.CharField(blank=True, max_length=30, null=True)),
                ('requested_by', models.CharField(blank=True, max_length=30, null=True)),
                ('ok_checklist', models.CharField(max_length=30, null=True)),
                ('faulty_checklist', models.CharField(max_length=30, null=True)),
                ('spare_used', models.CharField(blank=True, max_length=30, null=True)),
                ('labor_charge', models.CharField(blank=True, max_length=30, null=True)),
                ('total_cost', models.CharField(blank=True, max_length=30, null=True)),
                ('jobcard_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_media', models.FileField(blank=True, null=True, upload_to='jobcards/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_jobcards', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institution')),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ticket')),
            ],
            options={
                'ordering': ('-jobcard_created_at',),
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.institution'),
        ),
    ]
