# Generated by Django 4.2 on 2023-07-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='serial_number',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='ticket',
        ),
    ]
