# Generated by Django 4.2 on 2023-07-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_ticket_assigned_to_remove_ticket_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedJobCard',
        ),
    ]
